### ISSUE TITLE
Make an offline version of the program with current datasets

### ISSUE THREAD

**Issue by PetKosTuni** [PetKosTuni/Epidemic-model-of-COVID#15]

**Comment by Snibz** [comment]
Found a bug, validation for JHU nation-level datasets is broken. There is some issue with getting a datetime from the pandas dataframe of the dataset, unclear why this is happening. 
I will also attempt to fix the bug in this issue.

**Comment by Snibz** [comment]
Problem with the bug is related to Indexing of pandas dataframe. When the JHU csv:s are read to form dataframes of COVID data, the first row of the csv or the Index has a information of either Province/state, or Country/region, and only one of those is relevant decided by validation arguments. In case of province/state, when the dataframe is formed with pandas, the Index-object of the dataframe consists of a row of ['Province/State', date0, date1, ... (various dates)]. Then when a specific province/state is selected, for example US confirmed cases with confim_table['US'], the result is a Series object with an identical Index, but with actual confirmed cases values as well. Problem is, the 'Province/State' also must have a value as it is in the Index and thus part of the data for each row. The actual problem comes from attempting to convert the dates in the Index by forming a DateTimeIndex while having the area identifier string also in the index. And the identifier cannot really be removed, because then an exception happens when the data entries have a mismatch with their size in relation to the Index size.
Thinking of finding a solution is underway, this became more complicated than first assumed. Need to find a valid way of manipulating either the DataFrame or the Series.
